apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui-app
        image: react-frontend:113
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: sigmoid-acr

---

apiVersion: v1
kind: Service
metadata:
  name: ui-app
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

